appname: "EABPaste"
layout: "main"
charset: "UTF-8"
template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
plugins:
  IRCNotice:
    host: 'chat.freenode.net'
    nick: 'eab-pastes'
    name: 'Dancer::Plugin::IRCNotice'
    channel: '#eatabrick'
    type: 'message'
